// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrotbEXpM6k54ZOPRb9OYx_1QonxVi_U',
    appId: '1:518439793335:web:0e9519131e3f206891d332',
    messagingSenderId: '518439793335',
    projectId: 'cbc-learn-mate-001',
    authDomain: 'cbc-learn-mate-001.firebaseapp.com',
    storageBucket: 'cbc-learn-mate-001.firebasestorage.app',
    measurementId: 'G-5M2THCPR96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy71lqz5WmgzdWWZ4ODfcbPUolQfWdpIo',
    appId: '1:518439793335:android:a38927dd2bc01ae191d332',
    messagingSenderId: '518439793335',
    projectId: 'cbc-learn-mate-001',
    storageBucket: 'cbc-learn-mate-001.firebasestorage.app',
  );

}